title: The internet architecture
author: Catch2022
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to a page of the internet, 
 created by a novice,
 full of intent.

# social links
twitter_username: Catch_2022 # DO NOT include the @ character, or else the build will fail!
github_username:  catch2021 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
